### ISSUE TITLE
Document the teleop safety feature..

### ISSUE THREAD

**Issue by mmwise** [fetchrobotics/docs#30]
University of Tokyo was teleoping the robot and got near an obstacle. Then the robot would not drive forwared, which was confusing. We should document the safety feature that we have added to the teleop and add it to the FAQ

**Comment by mikeferguson** [comment]
We can certainly document this -- but just note that the robot never completely stops -- for a Fetch, it will slow to 0.1 m/s when basically in contact with something.

**Comment by ablasdel** [comment]
This will be resolved by https://github.com/fetchrobotics/docs/pull/32
