### ISSUE TITLE
update documentation to call out that the commands can be run on a real or simulated robot

### ISSUE THREAD

**Issue by mmwise** [fetchrobotics/docs#33]
Currently the documentation starts with how to run the simulator for navigation but then doesn't explicitly call out that the commands can be run on a real robot...

http://docs.fetchrobotics.com/navigation.html

**Comment by ablasdel** [comment]
Fixed with https://github.com/fetchrobotics/docs/pull/36
Also added some clarification in the Manipulation docs of a similar nature.
