### ISSUE TITLE
Add tutorial about how to setup desktop machine for interacting with robot

### ISSUE THREAD

**Issue by mikeferguson** [fetchrobotics/docs#43]

**Comment by mikeferguson** [comment]
Need to especially mention where meshes come from (local machine). Should probably also add this to the FAQ.

**Comment by dbking77** [comment]
To prevent confusing errors caused by non-standard networking setups, have a step that verifies network connection between desktop and robot (maybe roswtf?),    Then provide links to ROS docs for debugging problems.
 - http://wiki.ros.org/ROS/Troubleshooting
 - http://wiki.ros.org/ROS/NetworkSetup

**Comment by mikeferguson** [comment]
Cleaning up old tickets I've created that will likely never get done...
