### ISSUE TITLE
sudo password

### ISSUE THREAD

**Issue by arii** [fetchrobotics/docs#70]
The default sudo password for the fetch robot is not included in the manual.  What is the password?

**Comment by dbking77** [comment]
The password for sudo is the same password for user account it is being run from.   If sudo hasn't be run in a while, it will prompt for a the user's password as an extra security precaution:

The default fetch account information is available here : 
http://docs.fetchrobotics.com/computer.html

**Comment by dbking77** [comment]
Here's a link the Markdown:
https://github.com/fetchrobotics/docs/blob/master/source/computer.rst#default-user-account

**Comment by arii** [comment]
Not sure how I missed that.  Thanks for the info!

> The password for sudo is the same password for user account it is being run from. If sudo hasn't be run in a while, it will prompt for a the user's password as an extra security precaution:
> 
> The default fetch account information is available here :
> http://docs.fetchrobotics.com/computer.html
