### ISSUE TITLE
Packages not found in Manual install of Fetch robot packages

### ISSUE THREAD

**Issue by Wodehouse** [fetchrobotics/docs#82]
I got an "error 404" when installing fetch packages on a Fetch robot (of the robot type " _fetch-generic_"). I followed the [manual installation](https://docs.fetchrobotics.com/indigo_to_melodic.html#upgrading-your-robot-to-ros-melodic-ubuntu-18-04:~:text=the%20flash%20drive.-,MANUAL%20APPROACH%3A%2018.04%20Install%20and%20Installing%20ROS/Fetch%20Packages,-Important) instructions on the official Fetch website, and got the error at the step linked [here](https://docs.fetchrobotics.com/indigo_to_melodic.html#upgrading-your-robot-to-ros-melodic-ubuntu-18-04:~:text=Then%20install%20packages%20specific%20to%20the%20robot%20type). 

The website mentioned (http://packages.fetchrobotics.com/binaries/) does not seem to exist so the packages cannot be installed. Can you help me with this so I can download the necessary packages?

**Comment by moriarty** [comment]
@erelson or @bluryi this is because the source for the firmware was never released, it was built as a binary and hosted on a Fetch server, and if the packages are built from source the firmware binary is pulled in by a script I think in a CMake file somewhere if I remember correctly.

If the server is moved or changed due to Zebra acquisition this would break, it would also be broken on the ROS Build farm… there was discussion on how to handle this because in the future the ROS build farm might not allow pulling in outside binary sources for security.

**Comment by Wodehouse** [comment]
Thanks for the quick response! 
Is there a way I can solve this error or access the CMake file mentioned?

**Comment by erelson** [comment]
Thanks for the heads up! I'll take a look later today!  I haven't used the manual step since that was written.

In theory the packages server has everything from the old one (aka, yes it was re-implemented last year)

**Comment by moriarty** [comment]
```bash
export ROBOTTYPE=$(hostname | awk -F'[0-9]' '{print $1}')
# sudo apt install $ROBOTTYPE-melodic-config  # pending future availability
wget http://packages.fetchrobotics.com/binaries/$ROBOTTYPE-melodic-config.deb
sudo apt install ./$ROBOTTYPE-melodic-config.deb -y
```

these instructions assume the robot hostname starts with either `fetch` or `freight`

Follow the instructions but set ROBOTTYPE directly.

http://packages.fetchrobotics.com/binaries/fetch-melodic-config.deb

or 

http://packages.fetchrobotics.com/binaries/freight-melodic-config.deb

**Comment by erelson** [comment]
One possible clue I'm seeing is that you mention `fetch-generic`.  This would be the hostname if you have previously tried the installer, but something went wrong before the name changed to e.g. `fetch1234` or whatever the user enters at the install prompt.  

Can you share the full error and what previous steps you have tried?  I generally recommend the automated installer; if it's not working, I definitely want to correct that!

**Comment by Wodehouse** [comment]
I ran "echo $ROBOTTYPE" in the terminal, which shows that the type is "fetch-generic", but writing this in place of "$ROBOTTYPE" gives the same error as before.
I tried the automatic installer again and ran into an error when running the Fetch robotics installer: it failed to ping packages.ros.org. (even with a verified internet connection), so the files I need can't be downloaded. Could this be an issue on ROS' end or might it have to do with my network settings? I have attached an image of the error:
![PingError](https://user-images.githubusercontent.com/68673729/215799254-b9951154-a404-4463-af35-ab9df9862558.jpeg)

**Comment by erelson** [comment]
If you were to hypothetically re-tackle the manual install, you'd probably do `export ROBOT_TYPE=fetch`

The packages.ros.org issue might indeed be an issue with your network, or just the connection from that computer.

You can open a terminal with ctrl+alt+t to try `ping packages.ros.org` or `ping google.com` and other troubleshooting.  I'm able to ping the server, though, presently the pings hit a slightly different IP: 64.50.236.52 (probably a CDN or some such).

**Comment by Wodehouse** [comment]
I tried setting the name for the fetch robot to something else instead of fetch-generic, as suggested (using _export ROBOT_TYPE=fetch5_), and was able to complete the manual install that way. 
Failing to ping happened because of the policies of my network, so the automated installer should be fine for other networks. Thanks for all your help!

**Comment by erelson** [comment]
Thanks for the update!  I'll keep in mind falling back to alternatives to ping in the future, possibly.
